databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: "postgres://egivydb_user:XwkteeOvp5XpNQnlEyMVokYNjhmnyu9B@dpg-cegalphgp3jjdtilccb0-a/egivydb"
        fromDatabase:
          name: mysite
          property: connectionString
      - key: "5d6fabbc70c19bfbf8526b792f2273f3"
        sync: false